[dy.namic] 지하철 노선도 1 ~ 3 단계 pr입니다.
next-step/spring-subway-admin-kakao pull request #12
Opened 2021-01-17 21:55 UTC by kdy2000

2021-01-18 12:43 UTC, findstar requested changes
안녕하세요 dy. 제임스입니다.
지하철 미션 진행하시느라 수고 많으셨습니다.
몇가지 코멘트 남겼으니 확인부탁드립니다.
질문은 언제든지 환영입니다. DM 부탁드려요 😄 
계속 화이팅입니다.!

2021-01-18 12:43 UTC, findstar commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
동일한 라인이 중복되고 아래에도 있네요.

2021-01-18 12:43 UTC, findstar commented on src/main/java/subway/line/LineDao.java
> +    public boolean hasDuplicateName(String name) {
이 메서드는 현재 외부에서 호출하는 곳이 없으니 private 으로 선언하는 게 더 나아보입니다.
그리고 이런 경우에는 isExist 와 같은 메서드명을 사용합니다.

2021-01-18 12:43 UTC, findstar commented on src/main/java/subway/DuplicateException.java
> +public class DuplicateException extends RuntimeException {
개별 Exception 으로 분리하였네요 💯

2021-01-18 12:43 UTC, findstar commented on src/main/java/subway/section/SectionDao.java
> +        /* 전달된 새로운 section을 추가 */
Dao 에서 너무 많은 역할을 처리하고 있지는 않은가요? 
분리해보면 좋겠습니다.

2021-01-18 12:43 UTC, findstar commented on src/main/java/subway/line/LineController.java
> +        }
SectionDao 에서 StationIds 를 가져와서 로직을 처리하고 있습니다.

2021-01-22 04:25 UTC, kdy2000 commented
section에서 station객체를 소유하도록 하고 싶었는데, 그럴경우 sectionDao에서, db row를 section으로 mapping해주는 객체를 작성할수가 없었습니다. 외부에서 뭔가 injection? 을 해주던가 해야할것 같은데, 구현방법도 문제지만, 그렇게 하는게 바람직한가도 의문이었습니다. 그래서 section객체에서 그냥 stationId를 가지도록 하였습니다.

2021-01-25 05:01 UTC, findstar approved these changes
안녕하세요 제임스입니다. 
코멘트 드린 피드백 잘 반영해주셨네요. 
PR 머지하겠습니다.
다음단계에서는 패키지를 좀 더 잘 정리하도록 고민해주세요
그럼 계속 화이팅입니다. 💯

2021-01-25 05:01 UTC, merged