[teo.kkim 김태홍] 지하철 노선도 리뷰 요청 드립니다.
next-step/spring-subway-admin-kakao pull request #23
Opened 2021-01-18 16:34 UTC by kth496

## 질문

1. **메모리와 시간복잡도 트레이드오프**
미션의 `Section`을 기반으로 `Station`을 순서대로 만드는 과정에서 페어와 2가지 방법을 고려해보았습니다. 첫째는 맵을 이용해서 빠르게 구현하는 것이고, 둘째는 스트림을 순회하면서 매번 다음 `Section`을 찾게 하는 방법입니다. 전자의 방법을 사용하면 메모리 낭비가 심할 것이라 생각하여, 현재 두번째 방법으로 구현되어있습니다. 현업에서는 비슷한 상황이 발생할 때, 어떤 기준으로 알고리즘을 설계, 구현하는지 궁금합니다! 😃

2. LineResponse 의 디폴트 생성자
미션에서 사용하는 `LineResponse`에는 인자가 없는 생성자가 존재합니다. 사용하는 곳이 없어 지워보았는데 컴파일은 성공하지만 런타임에서 에러가 발생하는 것을 확인했습니다. 왜 이런 현상이 발생하는지 궁금합니다! 😃

2021-01-19 05:50 UTC, ljh131 requested changes
안녕하세요. 전체적으로 테스트가 많이 추가되면 좋겠습니다. 특히 2단계에 나와있는 구간 등록/제거에 관련된 모든 정상적인 케이스와 가능하시면 엣지 케이스도 추가해보시면 좋겠습니다.

2021-01-19 05:50 UTC, friediceday commented on src/main/java/subway/line/Section.java
> +public class Section {
섹션은 다른 라인, 스테이션 패키지와 마찬가지로 분리해보면 어떨까요

2021-01-19 05:50 UTC, friediceday commented on src/main/java/subway/line/Section.java
> +        return Objects.equals(lineId, section.lineId) && (Objects.equals(upStationId, section.upStationId) && Objects.equals(downStationId, section.downStationId)
가독성을 위해 줄바꿈과 괄호가 있었으면 좋겠습니다.

2021-01-19 05:50 UTC, friediceday commented on src/main/java/subway/line/LineController.java
> +public class LineController {
4단계에서 리팩터링하겠지만 로직은 서비스에 들어가는게 어떨까요

2021-01-19 05:50 UTC, friediceday commented on src/main/java/subway/line/LineDao.java
> +        String sql = "select * from line";
실제라면 리밋 없이 사용하진 않을 것 같습니다. ui에서 페이지네이션없이 되어있어서 아마 그랬을 것 같은데요, 그렇다면 최대 가져올 수 있는 개수 제약조건을 두면 어떨까요

2021-01-19 05:50 UTC, friediceday commented on src/main/java/subway/line/LineDao.java
> +    public int findByName(String name) {
find라면 객체 자체를 찾아야될 것 같은데 카운트를 하고있네요. 이름을 바꾸면 어떨까요?

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/line/LineService.java
> +    public List<Station> findStationsOfLine(Long lineId) {
라인을 가져오는 모든 스테이션을 가져오는 메서드 맞나요?
지금 코드를 보면 라인에 속한 섹션을 가져온 다음 h->t로 돌면서 각 섹션별 스테이션을 하나씩 쿼리하고 있습니다.
이런 종류의 쿼리를 N+1 쿼리라고 하는데요. 효율적이지 않습니다.

사실 스테이션이 lineid를 갖고있으면 간단하게 해결되지 않을까요?

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/line/LineController.java
> +
갈래길이라기보다는 중복 아닐까요?
그리고 중복인게 서버 잘못은 아니므로 에러코드는 500보다는 4xx가 더 적합합니다.

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/line/LineController.java
> +                    return ResponseEntity.status(500).build();
여기도 500으로 쓰고 전반적으로 에러처리가 500으로 퉁쳐져있는데요, 상세하게 구분해보면 좋겠습니다.
그리고 응답을 만들어 리턴하는 것 보다는 예외로 처리해보는 방식이 더 좋을 것 같습니다

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/line/LineController.java
> +                sectionDao.save(new Section(id, sectionRequest.getDownStationId(), section.getDownStationId(),
아래 로직과 유사한데 공통으로 빼보면 좋을 것 같습니다

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/line/LineController.java
> +            sectionDao.save(new Section(id, Line.HEAD, sectionRequest.getUpStationId(), 0));
여기도 아래와 로직이 중복되는데 공통화 해보면 어떨까요

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/line/LineController.java
> +    public ResponseEntity addSection(@PathVariable Long id, @RequestBody SectionRequest sectionRequest) {
메서드가 전반적으로 너무 깁니다.

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/line/LineController.java
> +        Sections sections = sectionDao.findSectionsByLineId(line.getId());
모든 섹션을 다 가져올 필요가 있나요? 상황에 따라서 필요한 것만 가져오면 되지 않을까요

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/line/LineService.java
> +        return sectionDao.findSectionsByLineId(lineId).size() <= 3;
상수로 하면 좋겠습니다

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/line/LineService.java
> +        return lineDao.findByName(lineName) != 0;
이게 개수 세는 메서드고, 그럼 존재하는지 확인하는데 굳이 개수를 다 셀필요는 없을 것 같아요. 존재하는지만 보려면 보통 리밋1으로 쿼리해서 있는지만 봐도 되니까요.

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/station/StationController.java
> +    private StationDao stationDao;
여기도 컨트롤러가 dao 접근하는 류의 로직을 직접 하는게 아니라 서비스에서 하는게 좋을 것 같습니다

2021-01-19 05:50 UTC, ljh131 commented on src/main/java/subway/line/Section.java
> +    public static final int VIRTUAL_DISTANCE = 0;
어떤 의도인지 궁금합니다.

2021-01-19 06:14 UTC, ljh131 commented
메모리와 시간복잡도 트레이드오프
미션의 Section을 기반으로 Station을 순서대로 만드는 과정에서 페어와 2가지 방법을 고려해보았습니다. 첫째는 맵을 이용해서 빠르게 구현하는 것이고, 둘째는 스트림을 순회하면서 매번 다음 Section을 찾게 하는 방법입니다. 전자의 방법을 사용하면 메모리 낭비가 심할 것이라 생각하여, 현재 두번째 방법으로 구현되어있습니다. 현업에서는 비슷한 상황이 발생할 때, 어떤 기준으로 알고리즘을 설계, 구현하는지 궁금합니다! 😃
-> 아마 제가 커멘트 드린 부분에 대한 내용 같은데요. 커멘트 참고해주세요.

LineResponse 의 디폴트 생성자
미션에서 사용하는 LineResponse에는 인자가 없는 생성자가 존재합니다. 사용하는 곳이 없어 지워보았는데 컴파일은 성공하지만 런타임에서 에러가 발생하는 것을 확인했습니다. 왜 이런 현상이 발생하는지 궁금합니다! 😃
-> 구체적으로 어떤 에러인가요? 아마 흔하게는 누군가가 해당 객체를 시리얼라이즈/디시리얼라이즈하기 위해 리플렉션을 사용할텐데, 그럼 디폴트 컨스트럭터로 객체를 생성하고 거기에 필드를 넣을 것입니다. 그런데 인자가 있는 컨스트럭터를 추가하면 디폴트 컨스트럭터가 없어지니 에러가 발생할 것이고요.

2021-01-20 04:55 UTC, kth496 commented on src/main/java/subway/line/Section.java
> +public class Section {
넵 분리해보겠습니다!

2021-01-20 04:56 UTC, kth496 commented on src/main/java/subway/line/Section.java
> +        return Objects.equals(lineId, section.lineId) && (Objects.equals(upStationId, section.upStationId) && Objects.equals(downStationId, section.downStationId)
너무 길게 작성했네요.. 적절히 줄바꿈하겠습니다 😃

2021-01-20 04:56 UTC, kth496 commented on src/main/java/subway/line/LineController.java
> +public class LineController {
최대한 서비스로 로직을 옮겨보겠습니다!

2021-01-20 04:57 UTC, kth496 commented on src/main/java/subway/line/LineDao.java
> +        String sql = "select * from line";
이 부분을 고려하지 못했네요.. 제약 조건을 생각해보겠습니다!

2021-01-20 04:58 UTC, kth496 commented on src/main/java/subway/line/LineDao.java
> +    public int findByName(String name) {
카운트를 나타내는 이름으로 고쳐보겠습니다 😃

2021-01-20 05:00 UTC, kth496 commented on src/main/java/subway/line/LineService.java
> +    public List<Station> findStationsOfLine(Long lineId) {
처음에는 말씀하신대로 스테이션이 라인의 아이디를 가지게 구현했습니다. 그런데 미션에서 주어진 schema.sql 을 살펴보니 스테이션 테이블에는 라인 아이디 컬럼이 존재하지 않더라구요..😭 그래서 어쩔 수 없이 변경했습니다. 이 부분은 어떻게 해결해야 할까요??

2021-01-20 05:00 UTC, kth496 commented on src/main/java/subway/line/LineController.java
> +                    return ResponseEntity.status(500).build();
넵 적절한 예외로 처리해보겠습니다!

2021-01-20 05:03 UTC, kth496 commented on src/main/java/subway/line/LineController.java
> +            sectionDao.save(new Section(id, Line.HEAD, sectionRequest.getUpStationId(), 0));
중복되는 부분이 많이 있네요.. 개선해보겠습니다!

2021-01-20 05:06 UTC, kth496 commented on src/main/java/subway/line/LineController.java
> +    public ResponseEntity addSection(@PathVariable Long id, @RequestBody SectionRequest sectionRequest) {
10줄을 기준으로 쪼개보겠습니다!

2021-01-20 05:07 UTC, kth496 commented on src/main/java/subway/line/LineController.java
> +        Sections sections = sectionDao.findSectionsByLineId(line.getId());
말씀하신대로 다 가져올 필요는 없을 것 같아요. 개선해보겠습니다 😃

2021-01-20 05:08 UTC, kth496 commented on src/main/java/subway/station/StationController.java
> +    private StationDao stationDao;
스테이션을 빼먹었네요.. 고쳐보겠습니다!

2021-01-20 05:11 UTC, kth496 commented on src/main/java/subway/line/Section.java
> +    public static final int VIRTUAL_DISTANCE = 0;
저와 페어가 라인의 섹션을 관리하는 방식으로 인해 생긴 값입니다. 저희는 링크드 리스트의 헤드와 테일 노드가 존재하는 것에 아이디어를 얻었습니다. 이렇게 하면 라인의 시작 지점을 쉽게 알 수 있기 때문이죠. 이때 헤드와 테일 노드는 실제 존재하지 않는 가상의 정거장이므로 실제 상행 하행 종점과의 거리는 0으로 설정하고자 했습니다. 이를 VIRTUAL_DISTANCE 라는 이름으로 표현했습니다!

2021-01-20 05:14 UTC, kth496 commented
@ljh131 리플렉션으로 인한 에러로 확인되었어요. 말씀해주신대로 디폴트 생성자를 제가 없애버려서 에러가 발생했습니다 😭 답변 감사합니다!!

2021-01-20 08:06 UTC, ljh131 commented on src/main/java/subway/line/LineService.java
> +    public List<Station> findStationsOfLine(Long lineId) {
스키마를 직접 만든게 아니었나보군요. 스키마를 반드시 그대로 해야 하나요? 변경할 수 없나요?
만약 그렇다고 하면 조인을 고려해봐도 좋을 것 같습니다.

2021-01-20 17:33 UTC, kth496 commented
피드백을 반영하여 최대한 수정과 추가를 해보았습니다!!

스프링 환경에서의 디버깅이 익숙지 않아서 생각보다 오래걸렸네요 😭😭

리팩터링 과정에서 아래와 같은 의문이 들었습니다.

1. 조인을 이용해서 N+1 문제를 해결했습니다. 이때 조인된 객체를 받아오기위해 `Section` 클래스를 상속받은 `NextSection`을 구현해서 사용했는데요. 이런식으로 구현하니까 `Sections` 일급 컬렉션의 사용이 굉장히 어려워져서 관련 로직을 제네릭으로 감쌀 수 밖에 없었습니다. 실제로 조인을 해야하는 상황에서는 매핑하는 객체를 전부 만들어야하나요?? 

2. 핵심이 되는 로직을 전부 도메인 객체로 보내려고 시도했습니다. 그런데 dao 객체와 연관되는 부분이 너무 많아서 어렵다고 느꼈습니다. dao가 연관되는 부분은 도메인으로 보내지 못하고 서비스 객체에 남겨두었는데요. 이런 상황에서 적절한 설계가 어떤 것인지 궁금합니다.

3. 앞선 질문의 연장선으로, 서비스 객체에서 여러 도메인의 dao를 참조해야하는 상황에서, 직접 참조하는것이 좋을까요? 현재 제가 구현한 모든 서비스 객체들은 자신의 dao는 직접 접근하지만, 다른 도메인으로 접근할때는 해당 도메인의 서비스를 거칩니다. 예를 들어, `LineService`는 `LineDao`에는 직접 접근하지만 그외에는 `XXXService`를 거쳐 접근합니다. 그런데 이렇게 만드니 순환참조가 발생하는 것 같아서 고민입니다. 좋은 방법이 있을까요??

2021-01-21 07:55 UTC, ljh131 requested changes
잘 수정하셨습니다.
조금 더 개선할 수 있을 부분들은 커멘트 드렸습니다. 질문이나 의견 있으시면 남겨주세요.

2021-01-21 07:55 UTC, friediceday commented on src/main/java/subway/exception/ElementDeleteExeption.java
> +public class ElementDeleteExeption extends RuntimeException {
삭제가 안되어야 하는 조건에서 발생하는 익셉션 같은데요, 그런 뜻을 분명히 나타내면 어떨까요

2021-01-21 07:55 UTC, ljh131 commented on src/main/java/subway/line/Line.java
> +    public static final long HEAD = 0;
무엇에 대한 상수인지 명확하게 나타냈으면 좋겠습니다. head id 이런 식으로요.

2021-01-21 07:55 UTC, ljh131 commented on src/main/java/subway/section/Section.java
> +    public static final int VIRTUAL_DISTANCE = 0;
더 좋은 용어가 없을까요? 저도 딱히 떠오르는게 없긴 하네요.
다른 커멘트에서도 얘기했지만 이렇게 되면 디스턴스를 별도로 관리해보는 것도 생각해볼만 할 것 같습니다.

2021-01-21 07:55 UTC, ljh131 commented on src/main/java/subway/section/SectionDao.java
> +    public Section findSectionWithGivenUpStationId(Long lineId, Long upStationId) {
with given -> by 이렇게 해도 괜찮지 않을까요

2021-01-21 07:55 UTC, ljh131 commented on src/main/java/subway/section/SectionService.java
> +        int count = sectionDao.countByGivenUpStaionId(lineId, stationId);
개수 없이 존재하는지만 체크하면 되지 않을까요.

2021-01-21 07:55 UTC, ljh131 commented on src/main/java/subway/station/StationService.java
> +    public List<StationResponse> getStationResponses() {
서비스에서 응답을 바로 내려주기보다는 컨트롤러에서 응답으로 변환하면 어떨까요

2021-01-21 07:55 UTC, ljh131 commented on src/main/java/subway/line/LineDao.java
> +        String sql = "select * from line limit 5";
상수로 하면 좋겠습니다. 그리고 5는 너무 적지 않을까요? 비지니스적 요구사항이 아니라 기술적 제약사항으로 넣으신 것 같은데요

2021-01-21 07:55 UTC, ljh131 commented on src/main/java/subway/station/StationDao.java
> +        String sql = "select * from station";
여기도 리밋이 있으면 좋겠습니다.

2021-01-21 07:55 UTC, ljh131 commented on src/main/java/subway/line/LineService.java
> +    private int zeroIfOneOfDistanceIsVirtual(int distance1, int distance2) {
메서드 명의 zero는 지금 저 상수가 0이라서 그렇지 나중에 바뀌면 의미가 통하지 않겠는데요.
그리고 동작도 보면, 둘중 하나가 버추얼일때 버추얼인데 그 외의 경우에는 합이므로 예를 들면 sum distance 이런식으로 해도 될 것 같아요. 

왜냐하면 여기서 distance라는거를 h, t에서는 버추얼로 표현하기로 했으니까요. 
그럼 더 생각해보면 distance를 여기서 계산하기보다는 별도 객체로 분리해보는 것도 생각해볼 만 할 것 같습니다

2021-01-21 07:55 UTC, ljh131 commented on src/main/java/subway/exception/ElementInsertException.java
> +public class ElementInsertException extends RuntimeException {
여기도 더 명확하면 좋겠습니다

2021-01-21 07:55 UTC, ljh131 commented on src/main/java/subway/section/SectionDao.java
> +        return new NamedSections(jdbcTemplate.query(sql, (resultSet, rowNum) -> new NamedSection(
가독성상 한줄에 몰아쓰지 말고 분리해보면 어떨까요

2021-01-21 08:19 UTC, ljh131 commented
조인을 이용해서 N+1 문제를 해결했습니다. 이때 조인된 객체를 받아오기위해 Section 클래스를 상속받은 NextSection을 구현해서 사용했는데요. 이런식으로 구현하니까 Sections 일급 컬렉션의 사용이 굉장히 어려워져서 관련 로직을 제네릭으로 감쌀 수 밖에 없었습니다. 실제로 조인을 해야하는 상황에서는 매핑하는 객체를 전부 만들어야하나요??
-> 객체를 만들지 않고 맵을 사용할 수도 있습니다. 참고로 위 N+1 문제는 조인이 아닌 다른 방식으로도 해결할 수 있을 것 같습니다.

핵심이 되는 로직을 전부 도메인 객체로 보내려고 시도했습니다. 그런데 dao 객체와 연관되는 부분이 너무 많아서 어렵다고 느꼈습니다. dao가 연관되는 부분은 도메인으로 보내지 못하고 서비스 객체에 남겨두었는데요. 이런 상황에서 적절한 설계가 어떤 것인지 궁금합니다.
-> 사실 개인마다 선호하는게 다릅니다. 개인적으로는 무리하게 로직을 넘겼다가 가독성 떨어지고 복잡해지는 것 보다는, 간결하고 단순하며 직관적인 코드를 선호합니다.

앞선 질문의 연장선으로, 서비스 객체에서 여러 도메인의 dao를 참조해야하는 상황에서, 직접 참조하는것이 좋을까요? 현재 제가 구현한 모든 서비스 객체들은 자신의 dao는 직접 접근하지만, 다른 도메인으로 접근할때는 해당 도메인의 서비스를 거칩니다. 예를 들어, LineService는 LineDao에는 직접 접근하지만 그외에는 XXXService를 거쳐 접근합니다. 그런데 이렇게 만드니 순환참조가 발생하는 것 같아서 고민입니다. 좋은 방법이 있을까요??
-> 순환 참조가 발생한다는 것 자체가 이미 두 객체가 깊이 연관되어있다는 뜻 아닐까 싶습니다. 해결책은 상황에 따라서 다를 것 같습니다. 예를 들어 서로 커플링이 심한 ㄱ, ㄴ 서비스가 있다면 단순히 ㄱ ㄴ 로 나누는게 아니라 기능적으로 분리하는 것도 생각해볼 것 같습니다. 그리고 이렇게 할 수 없거나 그래도 너무 크면 다른 dao를 접근하는 것도 생각해볼 수 있겠습니다.

2021-01-21 12:39 UTC, kth496 commented on src/main/java/subway/line/LineService.java
> +    private int zeroIfOneOfDistanceIsVirtual(int distance1, int distance2) {
`Distance` 로 분리해보겠습니다!

2021-01-21 13:36 UTC, kth496 commented on src/main/java/subway/section/SectionService.java
> +        int count = sectionDao.countByGivenUpStaionId(lineId, stationId);
`EXISTS` 를 사용해서 존재만 체크하게 수정하겠습니다!

2021-01-21 13:39 UTC, kth496 commented on src/main/java/subway/line/LineDao.java
> +        String sql = "select * from line limit 5";
앞서 말씀하신대로 현재 페이지네이션이 포함되지 않은 상태입니다. 그래서 오프셋이나 리밋을 어떤 값으로 할지 헷갈려서 임시로 넣어보았습니다 😭😭 어떻게 개선하는게 좋을까요??

2021-01-21 13:44 UTC, kth496 commented on src/main/java/subway/section/SectionDao.java
> +        return new NamedSections(jdbcTemplate.query(sql, (resultSet, rowNum) -> new NamedSection(
알아보기가 힘드네요.. 파라미터 단위로 구분해보겠습니다!

2021-01-21 13:50 UTC, kth496 commented
@ljh131 

답변 감사합니다! 학생 시절에는 쿼리의 효율에 대해 큰 고민을 해보지 않아서 대부분을 조인으로 해결해왔습니다..😭 조인말고 다르게 해결하는 방법은 어떤게 있을까요?? 검색해보니 자바 환경에서는 JPA 관련 N+1 문제 해결법만 나와있어서, JdbcTemplate을 사용하는 이번 미션에서 어떻게 적용해야할지 궁금합니다

2021-01-22 05:36 UTC, ljh131 commented
> @ljh131
> 
> 답변 감사합니다! 학생 시절에는 쿼리의 효율에 대해 큰 고민을 해보지 않아서 대부분을 조인으로 해결해왔습니다..😭 조인말고 다르게 해결하는 방법은 어떤게 있을까요?? 검색해보니 자바 환경에서는 JPA 관련 N+1 문제 해결법만 나와있어서, JdbcTemplate을 사용하는 이번 미션에서 어떻게 적용해야할지 궁금합니다

jpa나 jdbctemplate과는 관련이 없습니다. 예를 들어 section을 먼저 가져왔다고 하면 적절히 정렬 등을 처리하면서 필요한 id들을 모으고 쿼리를 한번 더 날려도 되지 않을까요?

2021-01-23 02:47 UTC, kth496 commented
@ljh131 

아하! 말씀하신대로 ` ... WHERE id IN (1, 2, 3...)` 과 같은 형태의 쿼리를 요청하여 해결할 수 있을 것 같습니다. 앞으로 쿼리 효율에 대한 고민을 계속하면서 공부해보겠습니다!

2021-01-23 02:56 UTC, kth496 commented
@ljh131 

피드백을 기반으로 다음과 같이 리팩터링했습니다 😃 


1. **예외 처리 클래스들은 이름에 의도가 드러나도록 수정했습니다.**

2. **거리 관련 로직을 Distance 객체로 분리했습니다.**
이때 Distance 로 만들면서 발생한 문제에 대한 고민이 있습니다. Section 의 getDistance 의 리턴은 무엇으로 해야할까요?

    - int 로 유지시키면 기존 로직을 고칠 필요가 없지만, 결국 sumDistance 를 해야하는 상황에서 파라미터로 int 두 개 를 전달합니다.
    - 이러면 값을 포장한 의미가 없는 것 같습니다.

    - Distance를 리턴하도록 변경하면 section.getDistance().getDistance() 형태로 게터를 두 번 써야합니다.
    - 일반적인 경우는 다 포장값을 쓸 수 있는데 sectionDao 같은 곳에서는 게터 두번써야하는걸 피할 수 없는 듯합니다.(프리미티브 값을 가져와야 해서)

    - 저는 포장의 의미를 살리기 위해 후자를 선택하고 dao는 어쩔 수 없이 조금 더럽게 작성하도록 했습니다.


3. **생성자를 여러개 두는건 상관쓰지 않아도 될지?**
Section 같은 클래스의 경우 생성자가 좀 많아보입니다. 줄일 수 있긴 한데 그러면 `new Section` 하는 부분의 코드가 더러워질 것 같아서 여러개의 생성자를 만들게 되었습니다.

4. 쿼리 리밋의 적절한 값은 어떤 것이 있을까요?
현재 페이지네이션이 적용되지 않아서 오프셋을 비롯한 적정값이 고민됩니다.

2021-01-25 05:54 UTC, ljh131 approved these changes
수고하셨습니다. 이번 단계는 머지하겠습니다.
커멘트 몇개 달았는데 질문하신 내용들이긴 하네요. 따로 답변 달겠습니다.

2021-01-25 05:54 UTC, ljh131 commented on src/main/java/subway/line/LineDao.java
> +        String sql = "select * from line limit 5";
이 부분 확인해주세요. 개수는 생각해보시고 적당히 1000개 정도로 넣어도 되지 않을까요...

2021-01-25 05:54 UTC, ljh131 commented on src/main/java/subway/section/Section.java
> +    public Section(Long lineId, Long upStationId, Long downStationId, int distance) {
distance객체를 만들었으니 객체로 받아도 되지 않을까요

2021-01-25 06:07 UTC, ljh131 commented
> @ljh131
> 
> 피드백을 기반으로 다음과 같이 리팩터링했습니다 😃
> 
> 1. **예외 처리 클래스들은 이름에 의도가 드러나도록 수정했습니다.**
> 2. **거리 관련 로직을 Distance 객체로 분리했습니다.**
>    이때 Distance 로 만들면서 발생한 문제에 대한 고민이 있습니다. Section 의 getDistance 의 리턴은 무엇으로 해야할까요?
>    
>    * int 로 유지시키면 기존 로직을 고칠 필요가 없지만, 결국 sumDistance 를 해야하는 상황에서 파라미터로 int 두 개 를 전달합니다.
>    * 이러면 값을 포장한 의미가 없는 것 같습니다.
>    * Distance를 리턴하도록 변경하면 section.getDistance().getDistance() 형태로 게터를 두 번 써야합니다.
>    * 일반적인 경우는 다 포장값을 쓸 수 있는데 sectionDao 같은 곳에서는 게터 두번써야하는걸 피할 수 없는 듯합니다.(프리미티브 값을 가져와야 해서)
>    * 저는 포장의 의미를 살리기 위해 후자를 선택하고 dao는 어쩔 수 없이 조금 더럽게 작성하도록 했습니다.
> 3. **생성자를 여러개 두는건 상관쓰지 않아도 될지?**
>    Section 같은 클래스의 경우 생성자가 좀 많아보입니다. 줄일 수 있긴 한데 그러면 `new Section` 하는 부분의 코드가 더러워질 것 같아서 여러개의 생성자를 만들게 되었습니다.
> 4. 쿼리 리밋의 적절한 값은 어떤 것이 있을까요?
>    현재 페이지네이션이 적용되지 않아서 오프셋을 비롯한 적정값이 고민됩니다.

2 -> distance 객체를 리턴하는게 자연스럽지 않을까요? 게터 두번쓰는게 너무 싫다면 섹션에서 distance int를 리턴하는걸 만드는 방법도 있을 것 같습니다.

3 -> 모두 동일 역할을 하면 컨스트럭터 여러개도 괜찮다고 생각합니다. 그렇지만 섹션은 기능에 비해 좀 많은 것 같네요. 중복되기도 하고요. 더러워진다고 얘기하신게 다른 객체 생성없이 하고싶어서 그러신 것 같은데요, 개인적으로는 객체들을 잘 조합해서 만들 수 있으면 적절한 객체지향 디자인이 아닐까 싶습니다.

4 -> 혹시 몰라 넣은 값이니 적당히 큰 값으로 하면 좋겠습니다. 너무 커서 문제될 정도가 아닌 이상 적으면 나중에 또 바꿔야하니까요.

2021-01-25 06:07 UTC, merged

2021-01-26 04:21 UTC, kth496 commented
@ljh131 

꼼꼼한 피드백 감사합니다!!