[jamal.park] 지하철 노선도 Step3 리뷰 요청드립니다.
next-step/spring-subway-admin-kakao pull request #29
Opened 2021-01-19 08:39 UTC by jypark5826

안녕하세요, 뉴크루 자말입니다.
손댈 부분이 많아 보이지만 너무 늦어지는 것 같아서 리뷰 요청드립니다.

2021-01-19 10:12 UTC, parkjoos requested changes
안녕하세요! 😁
지하철 노선도 리뷰를 하게된 jay 라고 합니다. 반갑습니다.
리뷰를 하면서 comment 가 많아져 좀 끊어서 가면 좋을것 같아 먼저 전달 드릴께요
크게 두가지 개선이 있으면 좋을것 같은데요 
Service 레이어를 만들면서 Controller 로 많은 기능들이 넘어 왔는데 Controller 에서 해야 하는 일들 까지 넘어온 부분 들이 있습니다. comment 참고해서 이부분들은 controller 에서 할 수 있도록 수정해 주시면 좋을것 같구요
Section 과 관련된 기능들을 좀더 정리해서 SectionService 쪽으로 분리해 보면 좋을것 같습니다. 일단 SectionDao 를 사용하는 기능들을 SectionService 로 옮긴다고 생각하고 해보면 좋을것 같아요

 그럼 코멘트 참고해서 리팩토링 해보시고 혹시 어려운 부분이나 질문은 언제든지 답글이나 슬랙으로 남겨주세요
그럼 화이팅 입니다. 👍

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/station/StationService.java
> +        Station newStation = stationDao.findByName(stationRequest.getName());
이런 부분은 필요가 없습니다. 
위에서 save 가 성공했다면 당연한 결과이고 실패했다면 exception 이 발생해서 여기까지 오지 않기 때문입니다. 
그냥 save 전에 Station 를 변수에 할당하고  이를 이용해서 바로 리턴하면 될것 같습니다.

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/station/StationDao.java
> +    public static final String FIND_ALL_SQL = "select * from STATION";
쿼리에 * 의 전체 프로젝션 표현보다
명시적으로 projection 하고자 하는 컬럼을 나열해 주는것이 
DB의 변화로부터 프로그램이 영향을 받지 않도록 설계 되는 방향인것 같아요
한번 컬럼을 나열해서 작성해 보면 좋을것 같습니다.

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/station/StationDao.java
> +    public static final String DELETE_SQL = "delete from STATION where id = ?";
constant 로 분리해 놓은 부분 좋네요 👍

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/LineService.java
> +    public ResponseEntity<List<LineResponse>> showLines() {
showLine 이라는 표현은 프론트에서 이 서비스로직을 통해 데이터를 가져와 실제로 보여주기 때문에
이렇게 이름을 지으셨을것 같아요

하지만 이 Service class 입장에서 한번 생각해보면 Line 데이터를 가져와서 가공하고 전달해주는 역할만 하고 있기 때문에
show 라는 표현보다는 그냥 데이터를 가져온다거나 찾는다 정도의 표현을 사용하는게 좋을 것 같네요

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/LineService.java
> +        Line newLine = lineDao.findByName(lineRequest.getName());
여기도 필요없는 DB 조회는 하지 말고 위쪽의 new Line(lineRequest) 을 변수에 할당하여 바로 사용하는 편이 좋겠습니다.

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/Line.java
> +    private int distance;
private Long upStationId;
private Long downStationId;
private int distance;

은 Section 의 속성으로 보여지는데요 Line 에 있는 정보는 어떤 역할인가요? 기점과 종점을 기록하기 위함인가요?
이곳에 중복되는 속성을 두어서 비정규화 하는 것 보다 Section 에 기점과 종점을 알 수 있는 형태로 스키마를 설계 하면 어떨까요?

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/Line.java
> +    }
LineRequest 은 Controller 에서 view 로 전달하기 위한 DTO 역할이라고 보여지는데요
Line 이라는 도메인 객체에서 LineRequest 에 의존을 하고 있으면 안될것 같습니다. 
Line 은 프로젝트 전체에서 많이 사용하게 되는 도메인 클래스 입니다. 딱 이 도메인이 하는일만 하고 view 쪽의 일에는 관여 하지 않는 편이 좋을 것 같아요 
이 메소드를 반대로 LineRequest 에서 LineRequest 의 정보를 가지고 Line 을 만들어 내도록 변경해 보면 어떨까요?

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/LineController.java
> +    @DeleteMapping(value = "/lines/{id}/sections")
이 Controller 의 모든 uri 가 lines 로 시작하네요
모든 method 에 lines 로 시작되도록 uriMapping 를 지정할 필요 없이
이 클래스 전체에 @RequestMapping 이라는 어노테이션을 이용해서 path 를 지정 할 수 있습니다.
그러면 이 Controller 는 lines path 에서만 사용할 수 있도록 역할 분리도 잘 지켜 질 수 있겠네요
한번 적용 해 보면 어떨까요?

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/LineController.java
> +        return lineService.createSection(id, sectionRequest);
id 라는 파라메터를 그냥 id 라고 하지 말고 lineId 라고 좀더 명시적으로 작성해 볼까요?
createSection 에 넘기는 id 가 어떤 id 인지 좀더 명확하게 정의할 필요가 있을것 같습니다.

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/LineController.java
> +        return lineService.deleteSection(id, stationId);
createSection 과 deleteSection 은 lineService 보다는 SectionService 가 더 어울리지 않을까요?

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/LineService.java
> +    public ResponseEntity<LineResponse> createLine(LineRequest lineRequest) {
lineDao.save 처럼 
LineService 도 클래스의 역할이 명확하다면 메소드 이름을 createLine 대신 create 로 단순화 할 수 있을 것 같습니다.

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/Section.java
> +    }
지난 미션에서 연습해 봤던 일급 컬렉션을 사용한다면 Sections 하는 클래스를 하나 만들수 있을것 같아요 그러면 위 메소드들도 Sections  클래스로 위임 할 수 있을 것 같습니다.

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/LineService.java
> +        return ResponseEntity.ok().body(LineResponse.getLineResponses(lines));
서비스 레이어에서 ResponseEntity 를 리턴하고 있는데요 
이 로직을 Controller 에서 사용하지 않고 다른 서비스나 다른 모듈에서 사용한다면 어떨까요?
ResponseEntity 로 변환하는 과정은 Controller 의 역할로 넘기고 Service 레이어 에서는 어떤 비즈니스 로직의 결과물만 넘겨주면 좋을것 같습니다.

2021-01-19 10:12 UTC, parkjoos commented on src/main/java/subway/line/LineService.java
> +        return ResponseEntity.ok().build();
위에 서 말한것과 같이 ResponseEntity 의 결과 처리는 Controller 에서 하고 update 에서는 void  로 리턴해도 좋아요
그리고 LineRequest 에서 new Line(id, lineRequest) 을 만드는 과정도 Service 레이어의 역할은 아닙니다. 
이 부분도 Controller 가 하게 하고 만들어진 Line 을 받아서 처리 할수 있도록 하면 좋을것 같습니다.

2021-01-20 08:50 UTC, jypark5826 commented
피드백 주신 부분 위주로 리팩토링 해보았습니다.
아직 손댈 부분이 많을 것 같은데 다시 리뷰 부탁드립니다:)

2021-01-20 10:41 UTC, parkjoos requested changes
리팩토링을 통해서 역할 분리가 되어서 훨씬 구조가 잘 잡힌 모습입니다. 👍
제가 코멘트를 통해서 패키지 구조 부분과
controller 에서 구현되어 있는 로직이 몇가지 Service 로 이동되었으면 하는 부분이 있는데요 
이부분 한번 정리해 보면 좋을것 같습니다. 
그외의 코멘트들은 다음 스텝에서 고도화 해보면 되는 내용들이라고 생각되니 참고만 먼저 해주세요

2021-01-20 10:41 UTC, parkjoos commented on src/main/java/subway/line/LineController.java
> +    @Resource
service 클래스 의존성을 주입할때 @Resource 어노테이션을 사용하셨는데요
@Autowired 나 @Resource 로 의존성을 주입하는 방식은 예전에 많이 사용하였는데 
요즈음은 거의 사용하지 않고 지양하기를 권장 드립니다. 
대신 이 세가지 서비스 클래스를 파라메터로 받는 생성자를 만드는 방식으로 의존성 주입을 하도록 권장하고 있어요 
그 이유는 가장 크게 유닛 테스트시에 컨테이너를 통째로 띄우지 않아도 된다 가 있구요 몇가지 이유가 더 있는데 아래 링크를 참조해 보시면 좋을것 같습니다.

https://www.google.co.kr/search?hl=ko&lr=&aq=f&oq=&q=constructor%20bean%20injection

2021-01-20 10:41 UTC, parkjoos commented on src/main/java/subway/line/Line.java
> +package subway.line;
지금 패키지 구조를 보시면 한군데에 너무 많은 클래스들이 모여 있는걸 볼 수 있는데요  
![image](https://user-images.githubusercontent.com/61861989/105153188-7e9faa80-5b4b-11eb-9b52-4fd7813fdac5.png)

controller - service - repository 레이어 구조를 만들어 두었으니 이 레이어 대로 구분을 지어 패키지를 구성해 보면 어떨까요?
구조가 잘 잡혀 있어야 이후 추가되는 요구사항들도 알맞게 위치 하기 쉽구요 
협업할때 다른 동료도 구조를 파악 하기 쉬워 집니다. 
아래 구조를 한번 참고 해 보세요
![image](https://user-images.githubusercontent.com/61861989/105154283-be1ac680-5b4c-11eb-802f-a0ea69d770b9.png)

2021-01-20 10:41 UTC, parkjoos commented on src/main/java/subway/line/LineController.java
> +                SectionService.NOT_LAST_SECTION);
이 부분도 lineRequest 에서 line 을 만든 것처럼 SectionRequest 에서 section 을 만들어 내면 좋을 것 같네요

2021-01-20 10:41 UTC, parkjoos commented on src/main/java/subway/line/LineController.java
> +        lineService.delete(lineId);
line 이 삭제 되면 section 은 당연히 함께 삭제 되는 비즈니스 로직을 가지게 될것 같은데요 
lineService에서 delete 를 할때 section 도 삭제 되도록 한번에 구현을 해도 되지 않을 까요?

2021-01-20 10:41 UTC, parkjoos commented on src/main/java/subway/line/LineController.java
> +        stationService.delete(stationId);
이렇게 되면 다른 구간 다른 라인에 매핑되어 있는 station 도 삭제 되어 버릴것 같은데요
station 삭제가 잘못 들어 간 것 아닌지 확인한번 부탈드려요

2021-01-20 10:41 UTC, parkjoos commented on src/main/java/subway/line/LineController.java
> +        sectionService.delete(lineId, stationId);
이부분도 validate 가 구간 삭제시 반드시 타야 하는 상황이라면 서비스 내의 delete 메소드 안에서 확인 되어도 될 것 같아요

2021-01-20 10:41 UTC, parkjoos commented on src/main/java/subway/line/Sections.java
> +                .collect(Collectors.toMap(Section::getUpStationId, section -> section));
section -> section 
이표현을 함수형 인터페이스로 Function.identity() 로 좀더 간단하게 표현 할 수 있습니다.

2021-01-20 10:41 UTC, parkjoos commented on src/main/java/subway/line/SectionService.java
> +        }
이부분 로직이 너무 복잡하고 이해하는데 어려움이 있는데요
좀더 쉽게 로직을 정리하면 

1. 기존의 전체 구간들 중에 추가될 downStation 이 들어갈 target 구간을 찾는 과정 
2. 그 구간에 downStation 을 집어 넣는 과정

두단계로 넣을 수 있을 것 같고 1번의 과정은 Sections 라는 일급 컬렉션으로 기능을 위임 할 수 있을 것 같은데요
한번 이렇게 리팩토링을 할 수 있을지 검토 부탁드립니다. 
그리고 아래 addUpStation 의 로직과도 거의 유사한데 이 두가지 로직을 하나의 로직을 합치는 것도 한번 도전해 보세요

2021-01-20 10:41 UTC, parkjoos commented on src/main/java/subway/station/StationController.java
> +                    sectionService.delete(line.getId(), stationId);
아까 앞서 있었던 sectionService.delete 내에 validate 가 내재 되었다면 이부분도 하나의 로직 call 로 해결이 될것 같네요
그리고 stationService.delete 자체에서 이 전체 로직을 구현하는 것도 좋을 것 같아요 
어차피 station 을 삭제하려면 위와 같은 과정을 거치는것이 당연하다면요

2021-01-20 10:41 UTC, parkjoos commented on src/main/java/subway/station/StationService.java
> +        Long upStationId = sectionDao.findFirstByLineId(lineId).getUpStationId();
이 부분은 위의 sections 에서 firstSection 인 애를 찾는 부분이랑 사실 같은데요 
이미 sections 전체를 프로그램의 메모리에 들고 있는 상태 에서 다시 DB 에서 데이터를 찾을 필요는 없는것 같습니다. 
전체 리스트를 순회하면서 찾는 부분이 비효율 적이라고 생각되면 Sections 내에 이를 빠르게 찾을 수 있는 자료구조를 도입해 보면 좋을 것 같아요 
헤더가 있고 바로 아래 나오는 로직처럼 꼬리를 물면서 찾아가는 자료구조가 하나 떠오르는게 있는데 LinkedList 랑 비슷하지 않나요?

2021-01-21 11:48 UTC, jypark5826 commented
꼼꼼한 피드백 감사드립니다:)
피드백 해주신대로 구조를 변경해보았습니다.

2021-01-22 02:34 UTC, parkjoos approved these changes
jamal 구조도 아주 보기 좋게 잡혔고
SectionService 로직도 너무 간결하게 리팩토링이 잘 되었네요 👍
더 이상 코멘트 드릴 내용이 없는 것 같아요 
정말 고생 맣으셨습니다. 👏
바로 머지 진행 하겠습니다.

2021-01-22 02:34 UTC, merged