[echo.ohce 김환석] 지하철 노선도 step4 리뷰 요청 드립니다.
next-step/spring-subway-admin-kakao pull request #47
Opened 2021-01-21 05:26 UTC by 10000sukk

안녕 하세요 에코입니다. 
이전 스텝을 하면서 이미 layout을 나눠놔서 크게 바뀌진 않고 이전에 머지 되면서 피드백 주신 사항들 위주로 고쳐 보았습니다.
많이 부족하지만 리뷰 부탁드립니다. 감사합니다😊

2021-01-21 14:41 UTC, Hue9010 requested changes
이전에 레이어를 구분해서 작업을 해주셔서 큰 변경 없이 잘 해주셨네요. 👍
몇가지 개선하면 좋을 것 같은 내용 코멘트 달았어요. 확인 해보시고 궁금한 부분은 질문 주세요. 😉

2021-01-21 14:41 UTC, Hue9010 commented on src/main/java/subway/controller/LineController.java
> +            System.out.println(lineRequest);
`System.out.prinln`!!
디버깅 용도로 작성하고 깜박하신 것 같네요. 😉

```java
public class PrintlnTest {
    @Test
    public void 출력하면서(){
        for(int i = 0; i < 10000; i++){
            System.out.println(i);
        }
    }

    @Test
    public void 출력없이(){
        for(int i = 0; i < 10000; i++){
        }
    }
}
```
위와 같이 새로운 테스트 클래스를 만들고 출력이 있을 때와 없을 때 테스트를 돌려보고 테스트 결과의 타임을 보세요. (0을 하나씩 더 붙여가면 더 극적인 결과를 볼 수 있을 겁니다.)
그 다음 실제 서비스에서 System.out.println을 왜 사용하면 안되는지 찾아보세요.

2021-01-21 14:41 UTC, Hue9010 commented on src/main/java/subway/controller/LineController.java
> +        }
전에 말씀드린 것 처럼 `ControllerAdvice`를 사용해 보세요. 큰 차이를 느낄 수 있을 겁니다!

2021-01-21 14:41 UTC, Hue9010 commented on src/main/java/subway/controller/LineController.java
>          }
```java
    public Line findLineByName(String name) {
        Line result = lineDao.findLineByName(name);
        if(result == null){
            throw new LineNotFoundException();
        }
        return result;
    }
```
Line을 못찾을 때는 500 에러보다는 더 적절한 status가 있습니다! 한번 status code를 찾아보세요!

2021-01-21 14:41 UTC, Hue9010 commented on src/main/java/subway/service/LineService.java
>              throw new LineNotFoundException();
사실 다른 곳보단 여기에 Optinal을 적용해보시는게 Optional을 경험해보기 좋을 것 같아요. 😉

2021-01-21 14:41 UTC, Hue9010 commented on src/main/java/subway/service/SectionService.java
> +            sectionDao.save(newSection);
Optinal로 받아왔는데 다시 Optinal로 감쌀 필요가 있을까요? 🤔 다르게 개선할 수 있을 것 같은데 한번 더 고민해봐 주세요!
우선 Optional을 경험해보는 차원에서 이곳에서 사용해보는걸 요청드린 점 참고부탁드려요!(여기와 이번에 Line쪽에 언급드린 곳 빼고는 굳이 바꾸실 필요는 없어요!)

나중에 한번 읽어보면 좋을 것 같아요. 😉
[Java Optional 바르게 쓰기](http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/)

2021-01-21 14:41 UTC, Hue9010 commented on src/main/java/subway/dto/LineResponse.java
> -
domain 이 dto 를 참조하면 여러 문제가 발생할수 있군요!😄 의존성을 제거 해 주었습니다! 감사합니다.
한가지 더 여쭤볼게 있는데요... lineRequest 에서
```java
public String getColor() {
return color;
}

public Long getUpStationId() {
    return upStationId;
}

public Long getDownStationId() {
    return downStationId;
}
```
이들은 쓰이는 곳도 없는데 없애면 테스트 실패가 됩니다.... 이유를 찾지 못했는데 혹시 알려주신다면 감사하겠습니다!

---
이거 답변은 관련성이 있어서 여기 드릴게요. json으로 변환하는 과정에서 getter를 사용합니다. 그래서 getter가 없는 필드는 json에서 제외가 됩니다.

```java
    public static ExtractableResponse<Response> 지하철_노선_생성_요청(LineRequest params) {
        return RestAssured
                .given().log().all()
                .contentType(MediaType.APPLICATION_JSON_VALUE)
                .body(params)
                .when().post("/lines")
                .then().log().all().
                        extract();
    }
```
body(params) 이곳이 문제(?) 되어 제대로된 요청이 가지 못한걸로 보이네요.
getter, setter를 제거 할 때는 참조되는 곳이 없어 보여도 실제로는 필요할 수 있어 조심시 지워야 합니다. 😢

2021-01-21 14:41 UTC, Hue9010 commented on src/main/java/subway/exception/LineNotFoundException.java
> +public class LineNotFoundException extends IllegalArgumentException{
IllegalArgumentException면 어떤 Response status code를 응답해야 할까요? 🤔
IllegalArgumentException을 상속 받은 커스텀 Exception이 모두 동일한 응답 코드를 사용한다면 try-catch에서도 IllegalArgumentException을 잡아서 핸들링 해줄 수 있을 것 같아요.

2021-01-25 15:48 UTC, 10000sukk commented on src/main/java/subway/controller/LineController.java
> +            System.out.println(lineRequest);
앞으로 절대 안써야 겟군요.....ㅜㅜ 알고리즘 할때 안좋은 습관이 들었네요 ..이제는 로깅으로 하는 습관!!😄 감사합니다!

2021-01-25 15:51 UTC, 10000sukk commented on src/main/java/subway/controller/LineController.java
> +        }
확실히 controller 에서 잡아 catch 해 줄 필요가 없어서 굉장히 깔끔해 졋습니다!. 하지만 한가지 궁금한 점이 있는데요.. 이게 전역으로 에러를 매핑해준다고 하는데 혹시 성능에서 괜찮은건가요?? 그리고 try catch 를 썻을 때는 코드는 더럽지만 그래도 어디에서 에러를 주의 해야 할지 명확히 보이는 반면에 ControllerAdvice 는 한눈에 보이지는 않는데 상관 없을까요??

2021-01-25 15:51 UTC, 10000sukk commented on src/main/java/subway/controller/LineController.java
>          }
Not_found 가 적당할거 같아요! 감사합니다 😄

2021-01-25 15:52 UTC, 10000sukk commented on src/main/java/subway/service/LineService.java
>              throw new LineNotFoundException();
Optional 정말 유용 하네요 ㅎㅎ 감사합니다

2021-01-25 15:52 UTC, 10000sukk commented on src/main/java/subway/service/SectionService.java
> +            sectionDao.save(newSection);
앗....미숙햇던거 같습니다..수정했습니다!

2021-01-25 15:54 UTC, 10000sukk commented on src/main/java/subway/dto/LineResponse.java
> -
감사합니다!! 저는 body 에 command + b 로 타고 들어가도 인터페이스 라서 모르겟더라구요...혹시 이럴때 쓰는 꿀팁 있을까요?? 어떻게 구현 되어 있는지 보려고 command + b 했는데 인터페이스인 경우요!

2021-01-25 15:56 UTC, 10000sukk commented
피드백 주셔서 정말 감사합니다! 주말에 이사 마무리 하느라 늦어졌네요..ㅎㅎ 더 미흡한점 알려주시면 감사하겠습니다!! 😄😄

2021-01-25 17:31 UTC, Hue9010 commented on src/main/java/subway/service/LineService.java
> +        return lineDao.findLineByName(name).orElseThrow(LineNotFoundException::new);
메서드 참조까지 👍 
참고로 Optinal과 Collection에 어떤 기능이 있는지 한두번씩 훑어 보면 많은 도움이 됩니다. 😉

2021-01-25 17:31 UTC, Hue9010 commented on src/main/java/subway/controller/LineController.java
> +        }
개인적으로 ControllerAdvice의 성능에 대해서 크게 고민을 해보진 않았군요. 🤔 스프링이 제공해주는 다양한 기능을 생각 해봤을 때 얼마나 차이 날지는 측정해봐야 할 것 같지만 서비스에 영향을 줄 정도로 차이 날 것 같지 않네요.
이참에 AOP의 개념에 대해서 간단히 찾아보시면 좋을 것 같아요. 😉

2021-01-25 17:37 UTC, Hue9010 commented on src/main/java/subway/dto/LineResponse.java
> -
위 답변은 경험에 의해서 답변드렸어요. 😢 
직접적으로 드러나지 않는 부분이라 이런 사항은 경험하면서 쌓이는 경향이 있어요. 테스트를 통해서 문제가 되는걸 알아차리 신 것처럼 테스트를 유용하게 사용하는 방법도 있을 것 같네요.

2021-01-25 17:40 UTC, Hue9010 approved these changes
잘 반영해주셨네요. 👍👍
이번 단계는 여기서 머지할게요. 코멘트로 문의주신 사항 답변드렸는데 혹시 놓친 부분 있으면 말씀주세요! 😉 
그 외에도 궁금한 사항은 언제든 질문주세요!!
고생하셨습니다. 다음 과정도 화이팅입니다!!

2021-01-25 17:40 UTC, Hue9010 commented on src/main/java/subway/handler/ControllerExceptionHandler.java
> +    private final Logger logger = LoggerFactory.getLogger(ControllerExceptionHandler.class);
로그를 배우지 않아 따로 말씀 안드렸는데 ControllerAdvice에 잘 사용해주셨네요. 😉 
System.out.println이 슬프게도 사용자가 적은 서비스라면 눈에 띌정도의 문제가 안생기지만.. 😢 사용자가 많은 서비스라면 바로 응답 지연이 발생 할 수도 있습니다. 게다가 당장은 사용자가 적었지만 많아지면 문제가 되겠죠.
여러모로 System.out.println은 실 서비스에서 사용을 지양하는게 좋습니다.

2021-01-25 17:40 UTC, merged

2021-01-27 08:12 UTC, 10000sukk commented
많이 배웠습니다! 지금까지 피드백 주셔서 정말 감사드립니다!!😄