[kuri.copper] 지하철 노선도 step4 리뷰 요청 드립니다.
next-step/spring-subway-admin-kakao pull request #48
Opened 2021-01-21 08:44 UTC by D-kuri

이전에 해주셨던 피드백 반영해보고 약간의 리팩토링 작업 해보았습니다.
계층 구조를 제 나름대로 적용해놓았다고 생각해서 큰 변경은 없었는데요 이와 관련해서 부족한점 피드백 주시면 감사하겠습니다 : D

2021-01-21 12:37 UTC, adeldel commented
안녕하세요. 4단계 잘 보았습니다. 지난번 리뷰때 드린 의견 중 두개 이상의 테이블에 저장 또는 수정을 같이 해야할 때 유의사항을 말씀드렸는데요.
예를 들면, LineService 의 `createLine`의 경우 line과 section 테이블에 모두 저장하고 있습니다.
line과 section 중 하나라도 저장 실패가 났을 경우 하나만 저장되고 하나는 실패한다면 데이터에 문제가 생기지 않을까요?
한 예로 section.distance 값이 디비에 Int 타입인데 엄청 큰 숫자가 들어오거나, line.name 값이 컬럼길이보다 긴 이름이 들어온다면 디비에러가 발생할 것 같습니다. 이러한 경우도 대비해야 데이터의 정합성이 지켜집니다. 
외래키를 생성하지 않았지만, 세 테이블 모두 서로의 id값을 참조하는 rdb 이므로 이 점을 고민해봐주세요.

2021-01-21 12:40 UTC, adeldel requested changes
안녕하세요 kuri 😸  리팩토링 해주신 내용 잘 보았습니다.
패키지 분류를 해주셨는데 일부는 변경 요청드렸어요.
그외 댓글로 남긴 내용이 있는데 확인부탁드려요.
조금만 더 힘내주세요 💪

2021-01-21 12:40 UTC, adeldel commented on src/main/java/subway/line/domain/LineDao.java
>  public class LineDao {
LineDao 클래스는 `domain -> dao` 패키지는 어떨가요? domain은 도메인객체만 모아두는게 좋을것 같아요.

2021-01-21 12:40 UTC, adeldel commented on src/main/java/subway/line/presentation/LineController.java
> +package subway.line.presentation;
`presentation` 레이어라서 패키지명을 이렇게 지으신거 같아요. 틀리진 않지만 보통 컨트롤러 클래스는 `controller` 라는 패키지로 모으기도 합니다.

2021-01-21 12:40 UTC, adeldel commented on src/main/java/subway/line/presentation/LineRequest.java
> +package subway.line.presentation;
요청/응답객체는 `dto` 나 `view`가 어떨까요?  (조직마다 다르므로 정답은 아니지만) 일반적으로 dto 패키지를 많이 씁니다.

2021-01-21 22:55 UTC, D-kuri commented
안녕하세요 아델 ! 
피드백 주신 내용대로 패키지를 조금 더 나누어 보았습니다. 데이터의 정합성을 지키기 위해 create 부분은 transaction으로 처리하고 삭제와 관련된 부분은 rdb의 foreign key를 사용하여 pk가 삭제될 경우 fk도 삭제되게끔 구현해보았습니다 : )

2021-01-22 00:06 UTC, adeldel approved these changes
안녕하세요. 리뷰요청 주신 내용 확인했고, 수정반영 해주셔서 감사합니다.
제가 드린 코멘트는  참고용으로 달아놓았습니다. 다음 미션도 화이팅하세요!
이번 미션은 여기서 마무리할께요.
수고 많으셨습니다. 🎉 🎉

2021-01-22 00:06 UTC, adeldel commented on src/main/resources/schema.sql
> +    foreign key(station_id) references STATION(id) on delete cascade,
foreign key를 생성하셨네요. (테이블 설계가 그렇다는거지 꼭 설정해야 한다는 얘기는 아니었어요 😅 ) 
사실 foreign key를 걸어두고  자동으로 삭제되도록 하면 편하긴 하지만 성능저하의 문제가 있어서 
(현재 저희 조직에서는)  외래키를 설정하지는 않아요. 그러므로 비즈니스 로직상 트랜잭션 관리가 중요합니다. 
이런 부분은 rdb에 대해 공부할때 좀 더 찾아보시면 좋을 것 같습니다.

2021-01-22 00:06 UTC, adeldel commented on src/main/java/subway/line/service/LineService.java
> +    @Transactional
`Transactional`  어노테이션을 쓰셨군요. 이 어노테이션을 쓸때는 잘 되겠거니 그냥 붙이면 안됩니다. 🙈  
에러 상황에서 기대하는대로 롤백이 잘 되는지 테스트가 중요합니다.
스프링 트랜젝션 동작원리나 옵션등에 대해 잘 아시고 쓰시길 바랍니다.
[참고자료](https://flowarc.tistory.com/entry/Spring-%ED%8A%B8%EB%9E%9C%EC%9E%AD%EC%85%98%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90)

2021-01-22 00:07 UTC, merged